import { useState } from "react"
import { Helmet } from "react-helmet-async"
import { FiArrowDownRight, FiArrowUpRight, FiCheck, FiDownload, FiGithub, FiLinkedin, FiMail, FiMenu, FiX } from "react-icons/fi"
import useCurrentLanguage from "../../hooks/useCurrentLanguage"
import usePDF from "../../hooks/UseGetPDFHook"
import { sendEmailService } from "../../api"

const copy = {
  es: { nav: ["Perfil", "Proyectos", "Experiencia", "Servicios", "Contacto"], eyebrow: "Hola · Allillanchu", title: "Desarrollador full stack para productos web que sí resuelven trabajo.", intro: "Combino Python y Django con React, Vue y TypeScript para crear CMS, herramientas internas, automatizaciones y experiencias web mantenibles.", primary: "Ver proyectos", secondary: "Hablemos", available: "Disponible para nuevas oportunidades", proof: ["Python · Django", "React · Vue · TypeScript", "APIs · CMS · Automatización", "Docker · CI/CD"], profileTitle: "Tecnología útil. Arquitectura clara. Entrega real.", profile: "Más de diez años entre informática, sistemas y desarrollo web. Mi foco actual: transformar necesidades operativas en productos digitales claros, sólidos y fáciles de mantener.", projectsTitle: "Proyectos que prueban el trabajo", projectsIntro: "Selección de producto público y verificable. Cada caso muestra una combinación concreta de arquitectura, interfaz y entrega.", all: "Todos", experienceTitle: "Experiencia y desarrollo continuo", servicesTitle: "Cómo puedo aportar", educationTitle: "Base técnica", contactTitle: "¿Construimos algo útil?", contact: "Estoy abierto a posiciones full stack, colaboraciones de producto y proyectos que necesiten una base técnica fiable.", name: "Tu nombre", email: "Tu email", message: "Cuéntame el contexto", send: "Enviar mensaje", sending: "Enviando…", sent: "Mensaje enviado. Te responderé pronto.", error: "No se pudo enviar. Escríbeme directamente por email.", footer: "Desarrollador full stack · Mataró, Barcelona", cv: "Descargar CV" },
  en: { nav: ["Profile", "Projects", "Experience", "Services", "Contact"], eyebrow: "Hello · Allillanchu", title: "Full-stack developer for web products that solve real work.", intro: "I combine Python and Django with React, Vue and TypeScript to build CMSs, internal tools, automations and maintainable web experiences.", primary: "View projects", secondary: "Let’s talk", available: "Open to new opportunities", proof: ["Python · Django", "React · Vue · TypeScript", "APIs · CMS · Automation", "Docker · CI/CD"], profileTitle: "Useful technology. Clear architecture. Real delivery.", profile: "Over ten years across IT, systems and web development. My current focus: turning operational needs into clear, robust and maintainable digital products.", projectsTitle: "Projects that prove the work", projectsIntro: "A selection of public, verifiable work. Each case shows a specific mix of architecture, interface and delivery.", all: "All", experienceTitle: "Experience and continuous development", servicesTitle: "How I can help", educationTitle: "Technical foundation", contactTitle: "Let’s build something useful.", contact: "Open to full-stack roles, product collaborations and projects that need a reliable technical foundation.", name: "Your name", email: "Your email", message: "Tell me about the context", send: "Send message", sending: "Sending…", sent: "Message sent. I will reply soon.", error: "Could not send it. Please email me directly.", footer: "Full-stack developer · Mataró, Barcelona", cv: "Download CV" },
}

const projects = [
  ["Curriculum CMS", "Producto", ["React", "Django REST", "Tailwind"], "CMS propio para gestionar un CV web, contenido bilingüe, contacto y portfolio.", "A custom CMS for a web CV, bilingual content, contact and portfolio.", "https://github.com/cdryampi/curriculum-frontend"],
  ["Gaudeix Codex", "Arquitectura", ["Django", "DRF", "Docker", "CI/CD"], "Reconstrucción modular de una plataforma de turismo, comercio y eventos municipales.", "Modular rebuild of a tourism, local commerce and municipal events platform.", "https://github.com/cdryampi/gaudeix-codex"],
  ["AI Suite", "IA aplicada", ["Python", "Flask", "Astro", "LLM"], "Plataforma local-first para ejecutar flujos de IA, miniapps, trabajos y artefactos.", "A local-first platform for AI workflows, mini apps, jobs and artifacts.", "https://github.com/cdryampi/ai-suite"],
  ["Task Inkor", "IA aplicada", ["Vue 3", "Supabase", "OpenAI"], "Gestor de tareas con asistencia contextual, etiquetado inteligente y experiencia responsive.", "A task manager with contextual assistance, smart tagging and responsive UX.", "https://github.com/cdryampi/task_inkor"],
  ["Tienda Django", "Ecommerce", ["Django", "Stripe", "PostgreSQL"], "Ecommerce con autenticación, carrito, pagos, idiomas y pipeline de despliegue.", "Ecommerce with authentication, cart, payments, languages and deployment pipeline.", "https://github.com/cdryampi/tienda-django"],
  ["Escandallo", "Producto", ["Laravel", "React", "Docker"], "Monorepo para una API REST y SPA con entorno reproducible en Docker/WSL.", "A monorepo for a REST API and SPA with a reproducible Docker/WSL environment.", "https://github.com/cdryampi/escandallo"],
]

const experience = [["2024 — hoy", "Desarrollo continuo", "Proyectos propios y práctica full stack en CMS, APIs, automatización, IA aplicada y despliegues."], ["2023 — 2024", "Ajuntament de Cabrera de Mar", "Desarrollo full stack de CMS, turismo, comercio local y gestión de eventos con Django y PostgreSQL."], ["2021 — 2023", "Epinium · Maneko · Inqbarna", "Desarrollo web y móvil, prototipado funcional, WordPress, Kotlin y soporte técnico."], ["2019 — 2021", "Güell Consulting", "Desarrollo Django, migraciones ecommerce, CRM, pruebas y resolución de incidencias."]]
const services = [["01", "Producto y backoffice", "CMS, paneles internos y herramientas que reducen trabajo manual."], ["02", "APIs e integraciones", "Servicios Django/REST y conexiones fiables entre datos, negocio y frontend."], ["03", "Frontend moderno", "Interfaces React, Vue o TypeScript accesibles, rápidas y pensadas para uso real."]]
const education = ["DAW · Desarrollo de Aplicaciones Web", "ASIX · Sistemas Informáticos y Redes", "Python Institute · Python Essentials 1"]

const HomePage = () => {
  const language = useCurrentLanguage() === "en" ? "en" : "es"
  const t = copy[language]
  const { data: pdfData } = usePDF()
  const [filter, setFilter] = useState(t.all)
  const [menuOpen, setMenuOpen] = useState(false)
  const [form, setForm] = useState({ name: "", email: "", message: "" })
  const [formState, setFormState] = useState("idle")
  const categories = [t.all, ...new Set(projects.map(([, category]) => category))]
  const visible = filter === t.all ? projects : projects.filter(([, category]) => category === filter)
  const pdfUrl = pdfData?.resume_file?.file
  const targets = ["perfil", "proyectos", "experiencia", "servicios", "contacto"]
  const submit = async (event) => { event.preventDefault(); setFormState("sending"); try { await sendEmailService(form.name, form.email, form.message); setFormState("sent"); setForm({ name: "", email: "", message: "" }) } catch { setFormState("error") } }

  return <main id="main-content" className="site-shell">
    <Helmet>
      <html lang={language} /><title>{language === "es" ? "Yanpiere Sánchez | Desarrollador Full Stack" : "Yanpiere Sánchez | Full-stack Developer"}</title><meta name="description" content={t.intro} />
      <meta property="og:type" content="profile" /><meta property="og:title" content="Yanpiere Sánchez | Full-stack Developer" /><meta property="og:description" content={t.intro} /><meta property="og:url" content={`https://yampi.eu/${language}`} /><meta property="og:image" content="https://yampi.eu/logo.png" /><meta name="twitter:card" content="summary_large_image" />
      <link rel="canonical" href={`https://yampi.eu/${language}`} /><link rel="alternate" hrefLang="es" href="https://yampi.eu/es" /><link rel="alternate" hrefLang="en" href="https://yampi.eu/en" />
      <script type="application/ld+json">{JSON.stringify({ "@context": "https://schema.org", "@type": "ProfilePage", mainEntity: { "@type": "Person", name: "Yanpiere Rafael Sánchez Gastelu", jobTitle: "Full-stack developer", url: "https://yampi.eu", sameAs: ["https://github.com/cdryampi", "https://www.linkedin.com/in/yanpiere-sanchez-gastelu/"] } })}</script>
    </Helmet>
    <header className="site-header"><a className="wordmark" href={`/${language}`}>YS<span>·</span>DEV</a><nav aria-label="Primary navigation" className="desktop-nav">{targets.map((target, index) => <a key={target} href={`#${target}`}>{t.nav[index]}</a>)}</nav><div className="header-actions"><a className="language-link" href={language === "es" ? "/en" : "/es"}>{language === "es" ? "EN" : "ES"}</a>{pdfUrl && <a className="icon-link" href={pdfUrl} target="_blank" rel="noreferrer" aria-label={t.cv}><FiDownload /></a>}<button className="menu-button" aria-expanded={menuOpen} aria-label="Menu" onClick={() => setMenuOpen((value) => !value)}>{menuOpen ? <FiX /> : <FiMenu />}</button></div>{menuOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{targets.map((target, index) => <a key={target} href={`#${target}`} onClick={() => setMenuOpen(false)}>{t.nav[index]}</a>)}</nav>}</header>
    <section className="hero section-grid" aria-labelledby="intro-title"><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1 id="intro-title">{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="button button-primary" href="#proyectos">{t.primary}<FiArrowDownRight /></a><a className="button button-secondary" href="#contacto">{t.secondary}<FiArrowUpRight /></a></div></div><aside className="hero-card" aria-label="Professional profile"><span className="availability"><FiCheck /> {t.available}</span><div className="monogram" aria-hidden="true">YS</div><p>Python / Django<br />React / Vue<br />Systems / Product</p><div className="hero-card-footer"><span>Barcelona</span><span>2026</span></div></aside></section>
    <section className="proof-strip" aria-label="Core skills">{t.proof.map((item) => <span key={item}>{item}</span>)}</section>
    <section id="perfil" className="section-grid section profile-section"><p className="section-index">01 / {language === "es" ? "PERFIL" : "PROFILE"}</p><div><h2>{t.profileTitle}</h2><p className="large-copy">{t.profile}</p></div></section>
    <section id="proyectos" className="section projects-section"><div className="section-heading"><div><p className="section-index">02 / WORK</p><h2>{t.projectsTitle}</h2></div><p>{t.projectsIntro}</p></div><div className="filter-row" aria-label="Project filters">{categories.map((category) => <button key={category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{category}</button>)}</div><div className="project-grid">{visible.map(([title, category, stack, spanish, english, href], index) => <a className="project-card" href={href} target="_blank" rel="noreferrer" key={title}><span className="project-number">0{projects.findIndex(([name]) => name === title) + 1}</span><FiArrowUpRight className="project-arrow" /><p className="project-category">{category}</p><h3>{title}</h3><p>{language === "en" ? english : spanish}</p><div className="tag-row">{stack.map((tag) => <span key={tag}>{tag}</span>)}</div></a>)}</div><a className="github-link" href="https://github.com/cdryampi" target="_blank" rel="noreferrer"><FiGithub /> GitHub / cdryampi <FiArrowUpRight /></a></section>
    <section id="experiencia" className="section experience-section"><div className="section-heading"><div><p className="section-index">03 / TIMELINE</p><h2>{t.experienceTitle}</h2></div></div><ol className="timeline">{experience.map(([date, title, description]) => <li key={title}><span>{date}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
    <section id="servicios" className="section services-section"><div className="section-heading"><div><p className="section-index">04 / SERVICES</p><h2>{t.servicesTitle}</h2></div></div><div className="service-grid">{services.map(([number, title, description]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="section education-section"><div><p className="section-index">05 / EDUCATION</p><h2>{t.educationTitle}</h2></div><ul>{education.map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section id="contacto" className="contact-section"><div><p className="section-index">06 / CONTACT</p><h2>{t.contactTitle}</h2><p>{t.contact}</p><div className="contact-links"><a href="mailto:yampiersanchezgastelu@gmail.com"><FiMail /> yampiersanchezgastelu@gmail.com</a><a href="https://www.linkedin.com/in/yanpiere-sanchez-gastelu/" target="_blank" rel="noreferrer"><FiLinkedin /> LinkedIn</a></div></div><form onSubmit={submit} aria-busy={formState === "sending"}><label>{t.name}<input required minLength="2" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>{t.email}<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>{t.message}<textarea required minLength="10" rows="4" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label><button className="button button-primary" disabled={formState === "sending"}>{formState === "sending" ? t.sending : t.send}<FiArrowUpRight /></button>{formState === "sent" && <p className="form-success" role="status">{t.sent}</p>}{formState === "error" && <p className="form-error" role="alert">{t.error}</p>}</form></section>
    <footer><span>{t.footer}</span><span>© {new Date().getFullYear()} Yanpiere Sánchez</span></footer>
  </main>
}
export default HomePage
